CREATE TABLE meows (
    meow_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userhandle TEXT NOT NULL, -- will later reference user_name from users table TEXT REFERENCES catshack_users(user_name) ON DELETE CASCADE NOT NULL,
    body TEXT NOT NULL,
    user_image TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    likeCount INTEGER DEFAULT 0 NOT NULL,
    commentCount INTEGER DEFAULT 0 NOT NULL
);